name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Detect Node version from .nvmrc
        id: node_version
        run: echo "nvmrc={value}" >> $GITHUB_OUTPUT

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.8'

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies and Puppeteer
        run: |
          npm ci
          sudo apt-get install libgbm-dev
          npm i puppeteer --no-save

      - name: Build Marp slide deck
        run: |
          echo "Debug: Checking Chrome path..."
          node .puppeteer.js
          echo "Debug: Chrome path found, starting build..."
          CHROME_PATH=$(node .puppeteer.js) npm run build --verbose
          touch ./dist/.nojekyll
        env:
          URL: https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}
          LANG: en-US
          DEBUG: "marp-cli:*,puppeteer:*"
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
